/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package titutorial.audiorecoder;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.media.MediaRecorder;
import android.os.Environment;


@Kroll.module(name="Audiorecoder", id="titutorial.audiorecoder")
public class AudiorecoderModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "AudiorecoderModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	// The JavaScript callbacks (KrollCallback objects)

	// output format constants
	@Kroll.constant public static final int OutputFormat_MPEG_4 = MediaRecorder.OutputFormat.MPEG_4;
	@Kroll.constant public static final int OutputFormat_THREE_GPP = MediaRecorder.OutputFormat.THREE_GPP;
	
	//audio encoder
	@Kroll.constant public static final int AudioEncoder_AAC = MediaRecorder.AudioEncoder.AAC;
	@Kroll.constant public static final int AudioEncoder_AMR_NB = MediaRecorder.AudioEncoder.AMR_NB;
	@Kroll.constant public static final int AudioEncoder_AMR_WB = MediaRecorder.AudioEncoder.AMR_WB;
	@Kroll.constant public static final int AudioEncoder_DEFAULT = MediaRecorder.AudioEncoder.DEFAULT;
	
	
	private MediaRecorder recorder = null;
	private String fullFileName = null;
	private String outPutFileName = null;
	private String AUDIO_RECORDER_FOLDER = "AudioRecorder";

	private KrollFunction successCallback = null;
	private KrollFunction cancelCallback = null;
	
	public AudiorecoderModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(TAG, "example called");
		return "hello world";
	}

	// Methods
	@SuppressWarnings("deprecation")
	private KrollFunction getCallback(final KrollDict options, final String name){
		return (KrollFunction) options.get(name);
	}

    public static String getSdCardPath() {
        return Environment.getExternalStorageDirectory().getPath() + "/";
    }
    
	private void sendSuccessEvent(String filepath)
	{
		if (successCallback != null) {
			Log.d(TAG, "inside: successCallback");
			Log.d(TAG, "filepath: "+filepath);
			String filepath1 = getSdCardPath() + filepath;
			String tmpPath = outPutFileName;
			Log.d(TAG, "getSdCardPath : "+getSdCardPath());
			Log.d(TAG, "tmpPath: "+tmpPath);
			Log.d(TAG, "after filepath: "+filepath);
			HashMap<String, String> event = new HashMap<String, String>();
			event.put("success", "true");
			event.put("filepath", filepath);
			event.put("filepath1", filepath1);
			event.put("filepath2", tmpPath);
			
			// Fire an event directly to the specified listener (callback)
			successCallback.call(getKrollObject(), event);
		}
	}
	
	private void sendCancelEvent(String message)
	{
		if (cancelCallback != null) {
			HashMap<String, String> event = new HashMap<String, String>();
			event.put("error", "true");
			event.put("message", message);
			
			// Fire an event directly to the specified listener (callback)
			cancelCallback.call(getKrollObject(), event);
		}
	}

	@Kroll.method
	public void registerCallbacks(HashMap args)
	{
		Object callback;
		
		Log.d(TAG,"[KROLLDEMO] registerCallbacks called");
		
		// Save the callback functions, verifying that they are of the correct type
		if (args.containsKey("success")) {
			callback = args.get("success");
			if (callback instanceof KrollFunction) {
				successCallback = (KrollFunction)callback;
			}
		}
		if (args.containsKey("cancel")) {
			callback = args.get("cancel");
			if (callback instanceof KrollFunction) {
				cancelCallback = (KrollFunction)callback;
			}
		}	
		
		Log.d(TAG,"[KROLLDEMO] Callbacks registered");
	}

	private String getFilename(int selectedFormat, String selectedFileName,  String selectedDirName) {
		String DirName = AUDIO_RECORDER_FOLDER;
		if(selectedDirName !=null && selectedDirName.length()>0){
			DirName = selectedDirName;
		}
		
		String fileName = System.currentTimeMillis()+"";
		if(selectedFileName !=null && selectedFileName.length()>0){
			fileName = selectedFileName;
		}
		
		String fileFormat = ".3gp";
		if(selectedFormat == OutputFormat_THREE_GPP){
			fileFormat = ".3gp";
		}else if(selectedFormat == OutputFormat_MPEG_4){
			fileFormat = ".mp4";
		}
		
		String sdCardPath = Environment.getExternalStorageDirectory().getPath();
		File file = new File(sdCardPath, selectedDirName);

		if (!file.exists()) {
			file.mkdirs();
		}
		
		outPutFileName = fileName + fileFormat;
		fullFileName = (file.getAbsolutePath() + "/" + outPutFileName);
		Log.d(TAG, "@@## fullFileName: " + fullFileName);
		return fullFileName;
	}
	
	@Kroll.method
	public void startRecording(HashMap args)
	{	
		KrollDict options = new KrollDict(args);
		int fileFormat = options.optInt("outputFormat", OutputFormat_THREE_GPP);
		int audioEncoder = options.optInt("audioEncoder", AudioEncoder_AMR_NB);
		String fileName = (String) options.get("fileName");
		String fileDirectory = (String) options.get("directoryName");
		Log.d(TAG, "fileFormat: " + fileFormat);
		Log.d(TAG, "fileName: " + fileName);
		Log.d(TAG, "fileDirectory: " + fileDirectory);
		registerCallbacks(args);
		
		recorder = new MediaRecorder();

		recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
		recorder.setOutputFormat(fileFormat);
		recorder.setAudioEncoder(audioEncoder);
		
		if (options.containsKey("maxDuration")) {
			int maxDurValue = options.optInt("maxDuration", 5000);
			Log.d(TAG, "@@## maxDurValue : " + maxDurValue);
            try {
            	recorder.setMaxDuration(maxDurValue);
            } catch (RuntimeException e) {
                Log.e(TAG,"setMaxDuration failed !");
            }
		}
		recorder.setOutputFile(getFilename(fileFormat, fileName, fileDirectory));

		try {
			recorder.prepare();
			recorder.start();
		} catch (IllegalStateException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}	
		
	}
	
	@Kroll.method
	private void stopRecording() {
		Log.d(TAG, "called: stopRecording");
		Log.d(TAG, "called: fullFileName = "+fullFileName);
		if (null != recorder) {
			recorder.stop();
			recorder.reset();
			recorder.release();

			recorder = null;
		}
		sendSuccessEvent(fullFileName);
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}

}

